### PR TITLE
Added details about scope

### PR DESCRIPTION
**Pull request by RichardLitt**
Thanks! See #11.

### CODE REVIEW

**Comment by IonicaBizau** [comment]
👍 Can you please add this in `package.json` because the README.md is generated?

Thanks!

**Comment by RichardLitt** [comment]
@IonicaBizau Looks like that was settled in #13?

**Comment by IonicaBizau** [comment]
Exactly. That workflow is not well documented. 🍀

**Comment by RichardLitt** [comment]
Nope! Only one way to fix it. :)

**Pull request merged**
